# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
---
github:
  description: "Apache Airflow Site Archive - archive of all produced documentation for Apache Airflow"
  homepage: https://airflow.apache.org/
  # Social media preview image is not supported by Github API/asf.yaml, need to be uploaded
  # manually in Github repository --> Settings --> click "Edit" in "Social preview"
  # See also:
  # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview
  # social_media_preview: github_repository_social_image.png
  features:
    # Disable issues management
    issues: false
    # Disable projects for project management boards
    projects: false
    # Disable wiki for documentation
    wiki: false
    # Disable discussions
    discussions: false

  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false

  pull_requests:
    # allow auto-merge
    allow_auto_merge: false
    # auto-delete head branches after being merged
    del_branch_on_merge: true

# Enable branch protection once this is setteled
#  protected_branches:
#    main:
#      required_pull_request_reviews:
#        required_approving_review_count: 1
#      required_linear_history: true
#      required_conversation_resolution: true
#      required_signatures: false

# Do not spam devlist with PRs and issues - do it like main repo
notifications:
  jobs: jobs@airflow.apache.org
  commits: commits@airflow.apache.org
  issues: commits@airflow.apache.org
  pullrequests: commits@airflow.apache.org
  discussions: commits@airflow.apache.org
