[project]
name = "airflow-site-archive"
version = "0.1.0"
description = "Airflow site archive for old/versioned docs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.11",
    "rich>=14.0.0",
]
