name: Basic checks
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: "Lint the repository"
    runs-on: ["ubuntu-22.04"]
    steps:
      - name: 🪓 Remove some stuff we don't need
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: "Install uv"
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} ) for scripts"
        uses: actions/checkout@v4
        # Checkout only workflow and scripts directory to run scripts from
        with:
          sparse-checkout: |
            .github
            scripts
      - name: 🔎 Lint
        run: |
          uv tool install pre-commit --with pre-commit-uv
          pre-commit run --all-files --color always
