# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: Sync GitHub to S3
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      destination:
        description: "The destination location in S3"
        required: true
        type: choice
        options:
          - live
          - staging
        default: live
      document-packages:
        description: "Packages (long or short) separated with spaces"
        required: false
        default: "all"
        type: string
      commit-reference:
        description: "Reference of commit used for the operation"
        required: false
        default: "main"
        type: string
      full-sync:
        description: "Sync everything rather than only changes from commit."
        required: false
        default: false
        type: boolean
      sync-registry:
        description: "Sync registry files to S3"
        required: false
        default: false
        type: boolean
      processes:
        description: "Number of processes to use for syncing"
        required: false
        default: "4"
        type: string
jobs:
  github-to-s3:
    name: GitHub to S3
    runs-on: ubuntu-latest
    steps:
      - name: Summarize parameters
        id: parameters
        env:
          DOCUMENT_PACKAGES: ${{ inputs.document-packages }}
          PROCESSES: ${{ inputs.processes }}
          DESTINATION: ${{ inputs.destination }}
          COMMIT_REFERENCE: ${{ inputs.commit-reference }}
          FULL_SYNC: ${{ inputs.full-sync }}
        run: |
          echo "Input parameters summary"
          echo "========================="
          echo "Destination: ${DESTINATION}"
          echo "Document packages: ${DOCUMENT_PACKAGES}"
          echo "Full sync: ${FULL_SYNC}"
          echo "Commit reference: ${COMMIT_REFERENCE}"
          echo "Processes: ${PROCESSES}"
          set -x
          if [[ "${DESTINATION}"  == "live" ]]; then
             echo "destination-location=s3://live-docs-airflow-apache-org/docs/" >> ${GITHUB_OUTPUT}
             echo "registry-destination-location=s3://live-docs-airflow-apache-org/registry/" >> ${GITHUB_OUTPUT}
          else
             echo "destination-location=s3://staging-docs-airflow-apache-org/docs/" >> ${GITHUB_OUTPUT}
             echo "registry-destination-location=s3://staging-docs-airflow-apache-org/registry/" >> ${GITHUB_OUTPUT}
          fi
          if [[ "${FULL_SYNC}" == "true" ]] ; then
            echo "sync-type=full-sync" >> ${GITHUB_OUTPUT}
          else
            echo "sync-type=single-commit" >> ${GITHUB_OUTPUT}
          fi
          echo "commit-ref=${{ env.COMMIT_REFERENCE }}" >> ${GITHUB_OUTPUT}

      - uses: actions/checkout@v4
        # Checkout only workflow and scripts directory to run scripts from
        with:
          sparse-checkout: |
            .github
            scripts

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a  # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Remove some stuff we don't need
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} ) for scripts"
        uses: actions/checkout@v4
        # Checkout only workflow and scripts directory to run scripts from
        with:
          sparse-checkout: |
            .github
            scripts

      - name: Create /mnt/cloned-airflow-site-archive directory
        run: |
          sudo mkdir -pv /mnt/cloned-airflow-site-archive
          sudo chown -R "${USER}" /mnt/cloned-airflow-site-archive
          ln -v -s /mnt/cloned-airflow-site-archive ./cloned-airflow-site-archive

      - name: Pre-process docs packages
        env:
          DOCUMENTS_PACKAGES: ${{ inputs.document-packages }}
        id: docs-packages-processed
        run: |
          echo "sparse-checkout<<EOF" >> ${GITHUB_OUTPUT}
          if [[ "${DOCUMENTS_PACKAGES}" != "all" ]]; then
            echo "Preprocessing docs packages: ${DOCUMENTS_PACKAGES}"
            packages=""
            sparse_checkout=""
            separator=""
            for package in ${DOCUMENTS_PACKAGES}; do
              if [[ "${package}" != apache-airflow-providers* ]]; then
                packages="${packages}${separator}apache-airflow-providers-${package/./-}"
                echo "docs-archive/apache-airflow-providers-${package/./-}" >> ${GITHUB_OUTPUT}
              else
                packages="${packages}${separator}${package}"
                echo "docs-archive/${package}" >> ${GITHUB_OUTPUT}
              fi
              separator=" "
            done
          else
            packages="all"
            echo "docs-archive" >> ${GITHUB_OUTPUT}
          fi
          echo "registry-archive" >> ${GITHUB_OUTPUT}
          echo "EOF" >> ${GITHUB_OUTPUT}
          set -x
          echo "docs-packages-processed=${packages}" >> ${GITHUB_OUTPUT}
      - name: >
          Checkout (${{  steps.parameters.outputs.commit-ref }}) to /mnt/cloned-airflow-site-archive
          with docs packages: ${{ steps.docs-packages-processed.outputs.docs-packages-processed }}
        uses: actions/checkout@v4
        with:
          path: ./cloned-airflow-site-archive
          fetch-depth: 2
          sparse-checkout: |
            ${{ steps.docs-packages-processed.outputs.sparse-checkout }}
          ref: ${{ steps.parameters.outputs.commit-ref }}
        if: steps.docs-packages-processed.outputs.docs-packages-processed != 'all'
      - name: >
          Checkout (${{  steps.parameters.outputs.commit-ref }}) to /mnt/cloned-airflow-site-archive (all packages)
        uses: actions/checkout@v4
        with:
          path: ./cloned-airflow-site-archive
          fetch-depth: 2
          ref: ${{ steps.parameters.outputs.commit-ref }}
        if: steps.docs-packages-processed.outputs.docs-packages-processed == 'all'
      - name: "Install uv"
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add staging watermarks
        # yamllint disable rule:line-length
        run: |
          curl -sSf -o add_watermark.py https://raw.githubusercontent.com/apache/airflow-site/refs/heads/main/.github/scripts/add_watermark.py
          chmod a+x add_watermark.py
          mkdir -p images
          curl -sSf -o images/staging.png https://raw.githubusercontent.com/apache/airflow-site/refs/heads/main/.github/scripts/images/staging.png
          uv run add_watermark.py --pattern 'main.min*css' --folder /mnt/cloned-airflow-site-archive/ \
          --image-directory images --url-prefix /images
        if: inputs.destination == 'staging'
      - name: >
          Syncing ${{ steps.parameters.outputs.commit-ref }}: ${{ inputs.destination }}:
          ${{ steps.parameters.outputs.sync-type }} ${{ steps.docs-packages-processed.outputs.docs-packages-processed }}
          wih parallel aws cli = ${{ inputs.processes }}
        env:
          COMMIT_REF: ${{ steps.parameters.outputs.commit-ref }}
          SYNC_TYPE: ${{ steps.parameters.outputs.sync-type }}
          DOCUMENTS_PACKAGES: ${{ steps.docs-packages-processed.outputs.docs-packages-processed }}
          DESTINATION_LOCATION: ${{ steps.parameters.outputs.destination-location }}
          PROCESSES: ${{ inputs.processes }}
        run: |
          # show what's being run
          set -x
          if [[ "${SYNC_TYPE}" == "single_commit" ]]; then
            echo "Syncing ${COMMIT_REF}"
          else
            echo "Syncing whole repo"
          fi
          ls -la /mnt/cloned-airflow-site-archive/*
          # we run inputs.processes aws cli commands - each command uploading files in parallel
          # that seems to be the fastest way to upload files to S3
          aws configure set default.s3.max_concurrent_requests 10
          uv run ./scripts/github_to_s3.py \
            --bucket-path ${DESTINATION_LOCATION} \
            --local-path /mnt/cloned-airflow-site-archive/docs-archive \
            --document-packages "${DOCUMENTS_PACKAGES}" \
            --commit-ref ${COMMIT_REF} --sync-type ${SYNC_TYPE} \
            --processes ${PROCESSES}
      - name: Syncing registry to ${{ inputs.destination }}
        env:
          REGISTRY_DESTINATION_LOCATION: ${{ steps.parameters.outputs.registry-destination-location }}
        run: |
          set -x
          aws s3 sync /mnt/cloned-airflow-site-archive/registry-archive/ "${REGISTRY_DESTINATION_LOCATION}" --delete
        if: inputs.sync-registry == true
