# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: Sync S3 to GitHub
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      source-location:
        description: "The source location in S3"
        required: true
        type: choice
        options:
          - s3://live-docs-airflow-apache-org/docs/
          - s3://staging-docs-airflow-apache-org/docs/
        default: "s3://live-docs-airflow-apache-org/docs/"
      document-folders:
        description: "Document folders to sync or short package ids (separated with spaces)"
        required: false
        default: "all"
        type: string
      commit-changes:
        description: "Commit changes to GitHub (forced to false if not main)"
        required: false
        default: true
        type: boolean
      processes:
        description: "Number of processes to use for syncing"
        required: false
        default: "4"
        type: string
jobs:
  s3-to-github:
    name: S3 to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Summarize parameters
        run: |
          echo "Source location: ${{ inputs.source-location }}"
          echo "Document folders: ${{ inputs.document-folders }}"
          echo "Commit changes: ${{ inputs.commit-changes }}"
          echo "Processes: ${{ inputs.processes }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a  # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Pre-process docs folders
        env:
          DOCUMENTS_FOLDERS: ${{ inputs.document-folders }}
        id: docs-folders-processed
        run: |
          echo "sparse-checkout<<EOF" >> ${GITHUB_OUTPUT}
          echo ".github" >> ${GITHUB_OUTPUT}
          echo "scripts" >> ${GITHUB_OUTPUT}
          if [[ "${DOCUMENTS_FOLDERS}" != "all" ]]; then
            echo "Preprocessing docs folders: ${DOCUMENTS_FOLDERS}"
            folders=""
            sparse_checkout=""
            separator=""
            for folder in ${DOCUMENTS_FOLDERS}; do
              if [[ "${folder}" != apache-airflow-providers* ]]; then
                folders="${folders}${separator}apache-airflow-providers-${folder/./-}"
                echo "docs-archive/apache-airflow-providers-${folder/./-}" >> ${GITHUB_OUTPUT}
              else
                folders="${folders}${separator}${folder}"
                echo "docs-archive/${folder}" >> ${GITHUB_OUTPUT}
              fi
              separator=" "
            done
          else
            folders="all"
            echo "docs-archive" >> ${GITHUB_OUTPUT}
          fi
          echo "EOF" >> ${GITHUB_OUTPUT}
          echo "docs-folders-processed=${folders}"
          echo "docs-folders-processed=${folders}" >> ${GITHUB_OUTPUT}

      - name: Create /mnt/cloned-airflow-site-archive directory
        run: |
          sudo mkdir -pv /mnt/cloned-airflow-site-archive && sudo chown -R "${USER}" /mnt/cloned-airflow-site-archive
          ln -sv /mnt/cloned-airflow-site-archive cloned-airflow-site-archive

      - name: >
          Checkout (${{  inputs.commit-sha || github.sha }}) to /mnt/cloned-airflow-site-archive
          with docs: ${{ steps.docs-folders-processed.outputs.docs-folders-processed }}
        uses: actions/checkout@v4
        with:
          path: ./cloned-airflow-site-archive
          fetch-depth: 1
          sparse-checkout: |
            ${{ steps.docs-folders-processed.outputs.sparse-checkout }}
        if: steps.docs-folders-processed.outputs.docs-folders-processed != 'all'

      - name: >
          Checkout (${{  inputs.commit-sha || github.sha }}) to /mnt/cloned-airflow-site-archive (whole repo)
        uses: actions/checkout@v4
        with:
          path: ./cloned-airflow-site-archive
          fetch-depth: 1
        if: steps.docs-folders-processed.outputs.docs-folders-processed == 'all'

      - name: "Check space available"
        run: df -h

      - name: Syncing ${{inputs.source-location}} (${{ inputs.document-folders }})
        env:
          PROCESSES: ${{ inputs.processes }}
        run: |
          set -x
          python3 -m pip install uv
          aws configure set default.s3.max_concurrent_requests 10
          uv run ./scripts/s3_to_github.py \
            --bucket-path ${{inputs.source-location}} \
            --local-path ./docs-archive \
            --document-folders "${{inputs.document-folders}}" \
            --processes "${{inputs.processes}}"
        working-directory: /mnt/cloned-airflow-site-archive

      - name: Diff summary
        run : |
          git diff --stat
        working-directory: /mnt/cloned-airflow-site-archive

      - name: Committing changes
        run: |
          echo "Running git config"
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          echo "Running git add"
          git add .
          echo "Running git commit"
          git commit -m "Sync S3 to GitHub" || echo "No changes to commit"
          git push --force origin main
        working-directory: /mnt/cloned-airflow-site-archive
        if: inputs.commit-changes == 'true' && github.ref == 'refs/heads/main'
